cmake_minimum_required(VERSION 3.5.0)
project(NextNewsSplat)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(splat SHARED napi_init.cpp splat.cpp renderer.cpp)
target_compile_options(splat PRIVATE -Wall -Wextra)
target_link_libraries(splat PUBLIC libace_napi.z.so libace_ndk.z.so libEGL.so libGLESv3.so libnative_window.so)
